language: node_js
node_js:
  - "11.0"
branches:
  only:
    - host
before_script:
  - npm install -g @angular/cli
script:
  - cd client
  - npm install
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch: host
  token:
    secure: "$FIREBASE_TOKEN"
